### ISSUE TITLE
cara membuat domain ke mail domain ( rasa penasaran stonk)

### ISSUE THREAD

**Issue by frostfire1** [Dhanamerdeka/NesiaGroup#1]
@Dhanamerdeka
cara ngebuat domain jadi domain mail gimana ya?
(atau dari host nya sendiri yang udah nyedia in)

**Comment by Dhanamerdeka** [comment]
> @Dhanamerdeka
> cara ngebuat domain jadi domain mail gimana ya?
> (atau dari host nya sendiri yang udah nyedia in)

maksudnya? gak faham aing?
kayak admin@nesia.my.id ?

**Comment by frostfire1** [comment]
> > @Dhanamerdeka
> > cara ngebuat domain jadi domain mail gimana ya?
> > (atau dari host nya sendiri yang udah nyedia in)
> 
> maksudnya? gak faham aing?
> kayak [admin@nesia.my.id](mailto:admin@nesia.my.id) ?

iya bang

**Comment by Dhanamerdeka** [comment]
> > > @Dhanamerdeka
> > > cara ngebuat domain jadi domain mail gimana ya?
> > > (atau dari host nya sendiri yang udah nyedia in)
> > 
> > 
> > maksudnya? gak faham aing?
> > kayak [admin@nesia.my.id](mailto:admin@nesia.my.id) ?
> 
> iya bang

klo dulu aku pakek vps (lebih gampang dan gak ada limit) klo sekarang pakek hosting biasa

**Comment by frostfire1** [comment]
oooooooo berarti dah di sediain ama hostingnya cpanelnya ya kak? emang pake hosting apa kak?

**Comment by Dhanamerdeka** [comment]
kalau beli hosting ntar ada menu generate email (tapi dibatasi)
klo mau unlimited. bisa beli VPS terus kita install panel sendiri, biar nanti bisa generate email sebanyak yang kita mau

**Comment by frostfire1** [comment]
> kalau beli hosting ntar ada menu generate email (tapi dibatasi)
> klo mau unlimited. bisa beli VPS terus kita install panel sendiri, biar nanti bisa generate email sebanyak yang kita mau

ooooo ok

**Comment by Dhanamerdeka** [comment]
anjer langsung di close XD
Klo situ mau langsung buat website aja, Ntar dikasih iklan, Lumayan uangnya buat jajan
